### ISSUE TITLE
no Bin folder on BB related to TeeVee

### ISSUE THREAD

**Issue by Norup123** [Digressive/Bash-Bunny-Payloads#1]
In the TeeVee payload it says the TeamViewer file needs to be in the bin folder.
There is no bin folder. Do you mean the Tools folder?
Also, the exe file in question is the teamviewer installer right? TeamViewer_Setup.exe ?

**Comment by Digressive** [comment]
Apologies for the confusion.
You can just create the bin folder manually - I didn't want to use the tools folder in this case (I honestly can't remember why). You can also just edit the script and use the tools folder.
And yes, by the exe I mean the TeamViewer_Setup.exe

Cheers,
-Mike

**Comment by Norup123** [comment]
Okay that makes more sense. I have added the file to the bin folder. Using the example'settings file, just renamed it to settings.reg.
You also say that you need to add the key at the end of the file for 64 bit systems, but the key you have posted is already there at the end.

Running the payload doesnt install teamviewer and leaves the loot\Teevee folder empty

You know if im doing something wrong here?

**Comment by Digressive** [comment]
It's ok, you're probably not doing anything wrong - I need to update the doc for sure.
To clarify some things:

The example-settings.reg file is there for testing without having to go through the trouble of creating your own, so your right in that you don't need to make any changes to it. If you do decide to create your own though, you should add the final line that's required.

For the install - you need to be running as an account with local admin privileges - the payload will send key presses to get by the UAC prompt but not if it requires a username and password. Additionally depending on the system it's running on, the wait times might need to be increased in the payload file otherwise it won't get past the UAC prompt..

**Comment by Norup123** [comment]
It was a language issue. Changed it to the correct one and now i can see that it atleast attempts to install teamviewer. Breaks along the way tho. Happened too fast for me to spot the problem. It created a txt file in the loot folder, but the file is empty

**Comment by Digressive** [comment]
The powershell script is the script responsible for installing team viewer, and exporting the ID to the txt file, so the Start-Sleep commands there might need increasing.

**Comment by Norup123** [comment]
I will try messing with the timings. Looking at the ps script it looks like the settings file needs to be called tv-settings.reg and be located in the bin folder, and not in the payload folder. Am i understanding this correct?

**Comment by Norup123** [comment]
![88175467_272427220409547_5416564057928892416_n](https://user-images.githubusercontent.com/54578187/76090661-425b6e00-5fbc-11ea-8cda-5a71b1e60797.jpg)
Now im getting this issue for some reason. The payload t.ps1 is still in the payload folder, so im not really sure what going on here =/

**Comment by Digressive** [comment]
No problem, lets see what we can do...

So, there's a couple of small problems with the first line in your PS window there should be this:

$pl = (gwmi win32_volume -f 'label=''BashBunny''').Name+'payloads\SWITCH1\t.ps1'"

you should be able to run it then.

The payload.txt file run on the BashBunny itself and it's Linux based, so there's extra characters and escape characters in the txt file so they can be sent to the Windows run box.

Hope this helps

**Comment by Norup123** [comment]
Hmm what the actual... My payload.txt looks like what you just posted. Why does it just skip the B in backbunny and the N in name? :S

Not sure what the issue is here, because the payload.txt file looks right

**Comment by Digressive** [comment]
Ok, I'm glad it worked! Not sure what was happening there.

I'm currently not sure about the site. A thought I had was to add an ALT+F4 keystroke to the end of the file after a short wait.

**Comment by Norup123** [comment]
Thats what i was thinking. But i think it has to be done in the t.ps right? The Bashbunny thinks its done way before the powershell script has finished running

**Comment by Digressive** [comment]
That's right. Two ways of doing it, the bashbunny payload would need to wait until the PS script had finished and then send the key strokes, or another way would be to kill the process from the PS script, but you'd have to know which browser was the default and then know to kill that process.

**Comment by Digressive** [comment]
I'm going to close the issue, but I'm happy to discuss further.
